# Overall
PROJECT_NAME=enfugue
AUTHOR_NAME=Benjamin Paine
AUTHOR_EMAIL=painebenjamin@gmail.com

COPYRIGHT_YEAR=2023
COPYRIGHT_COMPANY=Benjamin Paine

# Directories
BUILD_DIR=build
SRC_DIR=src
TEMPLATE_DIR=templates
VENDOR_DIR=vendor
SCRIPT_DIR=scripts
CONFIG_DIR=config

# Versioning
VERSION_MAJOR=0
VERSION_MINOR=1
VERSION_PATCH=3

# Files
DOCKERFILE=Dockerfile
LICENSE_FILE=LICENSE
NODE_PACKAGE=package.json

# Tool Binaries
PYTHON=python

# Built binaries
PYINSTALLER_SPEC=enfugue.spec
PYINSTALLER_SCRIPT=src/python/enfugue/enfugue.py
PYINSTALLER_NAME=enfugue-server

# Archive/distribution
ARCHIVE_SIZE=1960M

# Windows specific
WINDOWS_PYINSTALLER_DEPENDENCIES=flax\>=0.5,\<0.6 jax==0.3.25 jaxlib==0.3.25 -f https://whls.blob.core.windows.net/unstable/index.html

# Linux specific
LINUX_RUN_SCRIPT=enfugue.sh

# Environment
export KMP_DUPLICATE_LIB_OK=TRUE
